language: elixir
elixir:
  - 1.3.0
  - 1.3.1
  - 1.3.2
otp_release:
  - 18.2.1
  - 19.0.2

sudo: false

before_script:
  - MIX_ENV=test mix do deps.get
script:
  - MIX_ENV=test mix test
after_script:
  - MIX_ENV=test mix coveralls.travis
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report

